version: '3.8'

services:
  backend:
    build: ./
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /app/node_modules
      - logs:/app/logs
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  logs:
