version: '3.8'

services:
  backend:
    build: ./
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./:/app #bind method
      - /app/node_modules # anonymous volume
      - logs:/app/logs

volumes:
  logs:
